apiVersion: v1
kind: Service
metadata:
  name: chat-room-backend-service
spec:
  selector:
    app: chat-room-backend
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: LoadBalancer
  loadBalancerIP: 34.31.17.106
